#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run cspell to check for spelling errors
npx cspell '**/*.js' '**/*.ts' '**/*.md'

# If cspell finds errors, exit with status code 1 to block commit
if [ $? -ne 0 ]; then
  echo "Spelling errors found. Commit aborted."
  exit 1
fi
